#FTP上传目录
upper:
#  host: 10.10.3.201
#  host: 10.20.10.202
  host: 127.0.0.1
  port: 21
#  username: ar-san
#  password: ar-san@123
  username: wuhu
  password: 5720.wearable
  #文件传入目录
  fixedPath: \\

#FTP下载目录
lower:
#  host: 10.20.10.201
#  host: 10.10.3.202
#  port: 21
#  username: ar-san
#  password: ar-san@123
  host: 127.0.0.1
  port: 21
  username: test
  password: 12345678
  fixedPath: \\

#图纸固定ftp服务器
fixedftp:
  host: 127.0.0.1
  port: 21
  username: wuhu
  password: 5720.wearable
  #文件传入目录
  fixedPath: \\

#审计固定ftp服务器
fixedauditftp:
  host: 192.168.3.10
  port: 20
  username: wuhu
  password: 5720.wearable
  fixedPath: \\

#涉密网FTP服务器(前置机)路径
ftpUpperFolder: \\
#工控网FTP服务器（后置机）路径
ftpLowerFolder: \\
#部署本地上传暂存路径
localUploadFolder: E:\chcFTPTest\FTPStart\
#拉取文件本地存储目录
localDownloadFolder: D:\FTPDestination\

#该摆渡服务配置
server:
  port: 8090
